apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
  namespace: les-microservice
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: standard
