apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
  namespace: les-microservice
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data
