apiVersion: v1
kind: Service
metadata:
  name: platforms-svc
  namespace: les-microservice
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
    - name: http
      port: 80
      targetPort: 5012
      protocol: TCP
    - name: dapr-http
      port: 3500
      targetPort: 3500
      protocol: TCP
    - name: dapr-grpc
      port: 50001
      targetPort: 50001
      protocol: TCP
