apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: les-microservice
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://user:password@localhost:5672"
    - name: durable
      value: "false"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"
    - name: reconnectWait
      value: "5s"
    - name: concurrency
      value: "parallel"
scopes:
  - platformservice
  - commandsservice
